<?php
  /**
  * Modulo para la gestión de los entes planificadores
  * Sistema Automatizado para la Planificación Estratégico-Situacional en la Administración Pública Venezolana
  * @file ente_planificador.module
  * Drupal part Module to code ente planificador module
  * Copyright 2011 Sistema Automatizado para la Planificación Estratégico-Situacional en la Administración Pública Venezolana (CENDITEL)
  *
  * This program is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation; either version 2 of the License, or
  * (at your option) any later version.
  * 
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  * 
  * You should have received a copy of the GNU General Public License
  * along with this program; if not, write to the Free Software
  * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
  *
  * @author Cenditel Mérida TSU- Miguel Angel Narvaez Montilva
  * @see http://www.cenditel.gob.ve/
  * @see http://planificacion.cenditel.gob.ve/
  */

/*
 * Implementation of hook permission()
 */
// permisos administrativos para acceder al modulo 
function ente_planificador_permission() {
  return array(
    'admin planificador' => array(
      'title' => t('admin planificador'),
      'description' => t('Possibility of accessing to work with the module ente planificador and the functionalities incorporated in it.'),
    ),
    'ver planificador' => array(
      'title' => t('ver planificador'),
      'description' => t('Possibility of accessing to work with the module ente planificador and the functionalities incorporated in it.'),
    ),
    'edit own planificador' => array(
      'title' => t('edit own planificador'),
      'description' => t('Possibility of accessing to work with the module ente planificador and the functionalities incorporated in it.'),
    ),
    'edit all planificador' => array(
      'title' => t('edit all planificador'),
      'description' => t('Possibility of accessing to work with the module ente planificador and the functionalities incorporated in it.'),
    ),
    'admin all planificador' => array(
      'title' => t('admin all planificador'),
      'description' => t('Possibility of accessing to work with the module ente planificador and the functionalities incorporated in it.'),
    ),
  );
}

/*
 * Implementation of hook_help
 */
// ayuda del modulo 
function ente_planificador_help($path, $arg) {
  switch ($path) {
  // Ayuda general para el módulo Importar Terminos
    case 'admin/help#ente_planificador':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' .'The Ente PLanificador module allows registered users to register their entities'. '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<h3>' . t('help of the module Ente planificador ') . '</h3>'.'<br>';
      $output .= '<h4>' . t('Objetive of module:') . '</h4>';
      $output .= '<h4>' . t('Technical support') . '</h4>';
      $output .='<p>' . t('Contact us on the web for technical support or any questions <a href="@cenditel">cenditel</a>.', array('@cenditel' => url('http://planificacion.cenditel.gob.ve/contactos/'))) . '</p>';
    return $output;
  }  
}

//se crea el tipo de contenido ente planificador con el hook_node_info & hook_form
/*
 * Implementation of hook_node_info()
 */
function ente_planificador_node_info() {
  return array(
    'ente_planificador' => array(
      'name' => t('Ente Planificador'),
      'base' => 'ente_planificador',
      'description' => t('Ente planificador for Drupal 7.'),
    ),
  );
}

/*
 * Implementation of hook_form()
 */
function ente_planificador_form($node, &$form_state) {
}

/*ente_planificador
 * Implementation of hook_node_presave()
 */
function ente_planificador_node_presave($node) {
  if ($node->type =='ente_planificador') {
    $node->title = $node->field_razon_social['und'][0]['value']; 
    // the same information is saved from the field_razon_social in field  title
  }
}

/*
 * implementation of hook_menu()
 */
function ente_planificador_menu(){
  $items['administrar/entes_planificadores'] = array(    // <-- enlace url al modulo 
    'title' => 'Consultar lista de actores planificadores', // <-- titulo de hipervinculo en panel 
    'page callback' => 'entes_planificadores_views_list', // <-- función con la que trabaja 
    'access arguments' => array('admin planificador'), // <-- acceso restringido por hook  permission
    'type' => MENU_NORMAL_ITEM,
  );
  
  //enlace para verificar que sea un nodo real suplementando funcion ente_planificador_leer_ente_planificadores
  // %ente_planificador lee funcion ente_planificador_load($nid)
  $items['admin/people/create/%ente_planificador'] = array(
    'title' => 'Add user',
    //'page callback' => 'user_admin',
    //'page arguments' => array('create'),
    'access arguments' => array('administer users'),// verificar que el nodoe s de ente planificador.
    'type' => MENU_LOCAL_ACTION,
    //'file' => 'user.admin.inc',
  );
  /*
  $items['entes_planificadores/registrar'] = array(
    'title' => 'Registrar Actores Planificadores',
    'page callback' => 'entes_planificadores_agregar',
    'access arguments' => array('admin planificador'),
    'type' => MENU_NORMAL_ITEM,
  );
  */
  $items['admin/settings/ente_planificador'] = array(
    'title' => t('Configuración Ente Planificador'),
    'description' => t('Configuración del Ente Planificador.'),
    'access callback'=> TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/settings/ente_planificador/view'] = array(
    'title' => t('Ente Planificador'),
    'description' => t('Configuración de views del Ente Planificador.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ente_planificador_admin_settings_form'),
    'access callback'=> TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['administrar/entes_planificadores/registrar'] = array(
    'title' => 'Registrar Actores Planificadores',
    'page callback' => 'entes_planificadores_agregar',
    'page arguments' => array(1),
    'access arguments' => array('admin planificador'),
    'type' => MENU_NORMAL_ITEM,
  );

  //Item required to include tab in configuration ente planificador
  $items['admin/settings/ente_planificador/view/settings'] = array(
    //'title' =>  t('Configurar'),
    'access callback'=> TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => -10
  );

  $items['admin/settings/ente_planificador/view/default'] = array(
    'title' => t('Configuración de views'),
    'description' => t('Configuración de views del Ente Planificador.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ente_planificador_admin_settings_form'),
    'access callback'=> TRUE,
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -12
  );
  return $items;
}

/*
 * entes_planificadores_views_list
 * Lista de actores planificadores
 */
function entes_planificadores_views_list() {

//call the name and display of view can see in this function this is controller for ente_planificador_admin_settings_form

  if(variable_get('entepla_views', NULL) && variable_get('entepla_views_display', NULL)) {
    $view_name = variable_get('entepla_views', NULL);
    $view_page = variable_get('entepla_views_display', NULL);

    $view = views_get_view($view_name);
    $view->set_display($view_page);
    $view->pre_execute();
    $view->execute();
    $output = $view->render();
  }
  else{ 
    $loglink = l("aquí", 'admin/settings/ente_planificador/view');
    $msg = t("El modulo no esta configurado para configurarlo haga clic $loglink");
    $output = drupal_set_message($msg, $type = 'warning');
  }
  return $output;
} 

/**
 * entes_planificadores_agregar
 * Agregar un ente planificador
 */
function entes_planificadores_agregar() {
  drupal_goto('node/add/ente-planificador');
}

/*
 * Implementation of hook_form()
 */
function ente_planificador_admin_settings_form($form, &$form_state) {
  $form['description'] = array(
    '#type' => 'item',
    '#title' => t('List of views to manage in the system'),
  );

  $options = array();
  $entepla_views = views_get_all_views();
  foreach ($entepla_views as $view){
    $options[$view->name] = $view->human_name;
  }
  // form of select the list of views 
  $form['entepla_views'] = array(
    '#type'             => 'select',
    '#default_value'    => variable_get('entepla_views', NULL),
    '#required'         =>TRUE,
    '#title'            => t('selected the views.'),
    '#options'          => $options,
    '#description'      => t('List of available views '),
    '#ajax' => array(
      'callback' => 'ente_planificador_views_ajax_display', 
      'wrapper' => 'ajax_datos_display', 
      'effect' => 'fade',
      'event' => 'change',
      'method' => 'replace',
    ),
  );

  $form['views_container'] = array(
    '#type' => 'container', 
    '#prefix' => '<div id="ajax_datos_display">',
    '#suffix' => '</div>',
  );

  if (isset($form_state['values']['entepla_views']) || (variable_get('entepla_views', NULL))){

    $name = (isset($form_state['values']['entepla_views'])) ? $form_state['values']['entepla_views'] : variable_get('entepla_views', NULL);
    //$name = $form_state['values']['views'];
    $view =  views_get_view($name, 0);
    foreach ($view->display as $key => $display){
      $options_display[$key] = $display->display_title;
    }

    $form['views_container']['entepla_views_display'] = array(
      '#type'             => 'select',
      '#required'         =>TRUE,
      '#title'            => t('selected the type of view.'),
      '#default_value'    => variable_get('entepla_views_display', NULL),//call the value of form for system_settings_form 
      '#options'          => $options_display,
      '#description'      => t('List of available types of views'),
    );
  }
  $form = system_settings_form($form);//autosave information of the form.
  return $form;
}

/*
 * Implementation of function ente_planificador_views_ajax_display   
 */ 
function ente_planificador_views_ajax_display($form, &$form_state) {
  return $form['views_container'];
}

/**
 * Implementation of hook_views_api().
 */
function ente_planificador_views_api($module = NULL, $api = NULL) {
  return array(
    'api' => '3',
    'path' => drupal_get_path('module', 'ente_planificador') . '/views',
  );
}

/**
 * Implementation of hook_form_alter().
 */
function ente_planificador_form_alter(&$form, &$form_state, $form_id){
  if ($form_id == 'user_register_form'&& arg(3)) {
      $ente_planificador = arg(3); //The number of the planner entity of argument 3 given by the url is stored in the variable.
      $lang = $form['field_enteplanificador_user']['#language']; // lenguaje que se esta trabajando.
      $form['field_enteplanificador_user'][$lang]['#default_value'] = $ente_planificador; // it gives the value to the select.
      $form['field_enteplanificador_user']['#access'] = '0'; //hide the form field_enteplanificador_user.
  }
}

/**
 * Implementation of ente_planificador_load suplandado por ente_planificador_leer_ente_planificadores().
 * funcion para evitar la leida muchas veces de un ente planificador
 */
function ente_planificador_load($ente_planificador = 0) {
  //example https://api.drupal.org/api/drupal/includes%21common.inc/function/entity_get_controller/7.x
  $ente_planificadores = &drupal_static(__FUNCTION__); // guardado valor de nid en $ente_planificador_load
 
 // si es numerico y si no existe el arreglo $ente_planificadores[$ente_planificador] entra
  if (is_numeric($ente_planificador) && !isset($ente_planificadores[$ente_planificador])) {
    $ente_planificador_leido = node_load($ente_planificador); // carga nodo de la base de datos
    if ($ente_planificador_leido->type == 'ente_planificador') { // si es de tipo ente planificador 
     $ente_planificadores[$ente_planificador_leido->nid] = $ente_planificador_leido; 
     // agrega el nid del nodo a la variable ente_planificador_leido
    }
  } // si en un objeto $ente_planificador no exite la variable con un nid $ente_planificadores[$ente_planificador->nid]
  else if (is_object($ente_planificador) && !isset($ente_planificadores[$ente_planificador->nid])) {
    $ente_planificadores[$ente_planificador->nid] = $ente_planificador;
    $ente_planificador = $ente_planificador->nid;
  }
  else {
    //entra en memoria   
    //drupal_static_reset($name = 'ente_planificador_load'); // reset la variable.
    /*
    print '<pre>';
    print_r($ente_planificadores[$ente_planificador]);
    print '</pre>';*/
  }
/*
print '<pre>';
print_r($ente_planificadores);
print '</pre>';
*/

  return isset($ente_planificadores[$ente_planificador]) ? $ente_planificadores[$ente_planificador] : FALSE;

  //return $ente_planificadores;
}

/*
 * Implementation of hook_node_access
 */
function ente_planificador_node_access($node, $op, $account) {
  if ($op == 'view') {
    return user_access('ver planificador');
  }
  if ($op == 'create') {
    return ((user_access('edit all planificador'))||(user_access('admin planificador')));
  }
  if ($op == 'update') {
    if (user_access('edit all planificador') ||user_access('admin planificador') || (user_access('edit own planificador') && ($account->uid == $node->usuarios[$account->uid]))) {
      return TRUE;
    }
  }
  if ($op == 'delete') {
    return ((user_access('edit all planificador'))||(user_access('admin planificador')));
  }
}